version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:682227818354:task-definition/DemoTaskDefinition:5"
        LoadBalancerInfo:
          ContainerName: "DemoAppContainer"
          ContainerPort: 3000
#        # Optional properties
#        PlatformVersion: "LATEST"
#        NetworkConfiguration:
#          AwsvpcConfiguration:
#            Subnets: ["subnet-1234abcd","subnet-5678abcd"]
#            SecurityGroups: ["sg-12345678"]
#            AssignPublicIp: "ENABLED"
#        CapacityProviderStrategy:
#          - Base: 1
#            CapacityProvider: "FARGATE_SPOT"
#            Weight: 2
#          - Base: 0
#            CapacityProvider: "FARGATE"
#            Weight: 1
Hooks:
#  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
#  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:682227818354:function:AfterAllowTestTraffic"
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"
